import os
import sys
import logging
from logging.config import fileConfig

from alembic import context
from alembic.config import Config
from sqlalchemy import engine_from_config, pool

# ---------------------------------------------------------------------------
# Resolve paths: ensure project root is importable and load root-level alembic.ini
# ---------------------------------------------------------------------------
HERE = os.path.dirname(__file__)
PROJECT_ROOT = os.path.abspath(os.path.join(HERE, ".."))

# Make project root importable (so `from database import db` or `from app.database import db` works)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

# Explicit path to alembic.ini at project root
ALEMBIC_INI = os.path.join(PROJECT_ROOT, "alembic.ini")
if not os.path.exists(ALEMBIC_INI):
    raise FileNotFoundError(f"alembic.ini not found at expected location: {ALEMBIC_INI}")

config = Config(ALEMBIC_INI)

# use the alembic.ini for logging config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")
# ---------------------------------------------------------------------------
# Try to obtain SQLAlchemy MetaData from common locations.
# Primary attempt: import `db` from top-level `database.py` (project root).
# If that fails, target_metadata will be None and autogenerate will be disabled.
# ---------------------------------------------------------------------------
target_metadata = None


try:
    from app.database import db
    target_metadata = db.Model.metadata
    logger.info("Using target_metadata from app.database.db")
except Exception:
    # If neither import works, warn and continue; autogenerate will be disabled.
    logger.warning(
        "Could not import db from 'database' or 'app.database'. "
        "Autogenerate is disabled. Error: %s", e
    )
    target_metadata = None

# If you prefer to load sqlalchemy.url from your Flask config, you can set it in alembic.ini
# or modify this file to import your Flask app factory and set config.set_main_option('sqlalchemy.url', <uri>).

# ---------------------------------------------------------------------------
# Offline/online migration functions
# ---------------------------------------------------------------------------

def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine.
    """
    url = config.get_main_option("sqlalchemy.url")
    if not url:
        raise RuntimeError(
            "No sqlalchemy.url configured for offline migrations. Set sqlalchemy.url in alembic.ini."
        )
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode (create engine and connect)."""

    # This callback avoids creating an autogenerated migration file when there are no changes.
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, "autogenerate", False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info("No changes in schema detected.")

    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=process_revision_directives,
            # If you need other options, add them here (e.g. compare_type=True)
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# Execute the appropriate path
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
