"""added threshold column in Task

Revision ID: 59fc6d90063a
Revises: f627abf7a6fb
Create Date: 2025-12-02 09:12:28.530285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fc6d90063a'
down_revision = 'f627abf7a6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'threshold')
    # ### end Alembic commands ###
