"""no change migration

Revision ID: f627abf7a6fb
Revises: 976928c277c2
Create Date: 2025-12-02 09:03:28.342453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f627abf7a6fb'
down_revision = '976928c277c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
